version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8080:80
    